#---- Dirs ----
# input dirs
assemblies_dir: "data_input/assemblies/"
reads_dir: "/mnt/tank/scratch/skliver/common/pinnipeds/pusa_sibirica/male/trimmomatic/"

# output dirs
out_alignment_dir: "data_output/alignment"
varcall_dir: "data_output/varcall"

# technical dirs
scripts_dir: "workflow/scripts"

# log dirs
log_dir: "logs"
cluster_log_dir: "cluster_logs"
benchmark_dir: "benchmarks"

# config
conda_config: "workflow/envs/conda.yaml"

# parameters
reads: ["male_paired_trimmed"] # name of files with reads without suffixes (names should end by _1 for forward, _2 for reverse)
assembly: "draft_HiC" # name of file with assembly
min_mapping_quality: 20
bcftools_mpileup_annotate: "AD,INFO/AD,ADF,INFO/ADF,ADR,INFO/ADR,DP,SP,SCR,INFO/SCR"
bcftools_call_annotate: "GQ,GP"
bcftools_mpileup_max_depth: 250
bcftools_mpileup_min_MQ: 30
bcftools_mpileup_min_BQ: 30
bcftools_filter_soft_filter: "LowQual"
bcftools_filter_exclude: "QUAL < 20.0 || (FORMAT/SP > 60.0 | FORMAT/DP < 5.0 | FORMAT/GQ < 20.0)"

#---- Extensions ----
assemblies_ext: "fasta"
reads_ext: "fastq"

#---- Threads ----
bwa_index_threads: 30
bwa_map_threads: 30
bwa_mem_threads: 19
samtools_fixmate_threads: 1
samtools_sort_threads: 7
samtools_markdup_threads: 3
index_bam_threads: 30
mosdepth_threads: 16
bcftools_varcall_threads: 32

#---- Time ----
bwa_index_time: "12:00:00"
bwa_map_time: "24:00:00"
index_bam_time: "12:00:00"
mosdepth_time: "12:00:00"
bcftools_varcall_time: "100:00:00"

#---- Memory ----
# suppl
bwa_map_per_thread_mem_mb: 10
# rules
bwa_index_mem_mb: 30000
bwa_mem_mem_mb: 50000
samtools_fixmate_mem_mb: 20000
samtools_markdup_mem_mb: 20000
index_bam_mem_mb: 10000
mosdepth_mem_mb: 10000
bcftools_varcall_mem_mb: 100000