#---- Dirs ----
# input dirs
assemblies_dir: "data_input/assemblies" #"/mnt/archive/lgd_data/Mammals/pinnipeds/pusa_sibirica/genome/denovo/assemblies/hic_0.1/"
reads_dir: "data_input/reads" #"/mnt/archive/lgd_data/Mammals/pinnipeds/pusa_sibirica/genome/denovo/reads/raw/pe/female/"

# output dirs
out_alignment_dir: "data_output/alignment"

# technical dirs
scripts_dir: "workflow/scripts"

# log dirs
log_dir: "logs"
cluster_log_dir: "cluster_logs"
benchmark_dir: "benchmarks"

# config
conda_config: "workflow/envs/conda.yaml"

# parameters
reads: ["cerevisiae"] # name of files with reads without suffixes (names should end by _1 for forward, _2 for reverse)
assembly: "s.cerevisiae" # name of file with assembly
min_mapping_quality: 20

#---- Extensions ----
assemblies_ext: "fasta"
reads_ext: "fastq"

#---- Threads ----
bwa_index_threads: 20
bwa_map_threads: 20
index_bam_threads: 10
mosdepth_threads: 10

#---- Time ----
bwa_index_time: "12:00:00"
bwa_map_time: "24:00:00"
index_bam_time: "12:00:00"
mosdepth_time: "12:00:00"

#---- Memory ----
# suppl
bwa_map_per_thread_mem_mb: 1
# rules
bwa_index_mem_mb: 30000
bwa_map_mem_mb: 30000
index_bam_mem_mb: 10000
mosdepth_mem_mb: 4000